# Generated by Django 5.0.4 on 2025-02-19 14:30

from django.db import migrations

def change_age_group(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')
    people = person.objects.all()

    for p in people:
        if p.age <= 12:
            p.age_group = 'Child'
        elif p.age >= 18:
            p.age_group = 'Adult'
        else:
            p.age_group = 'Teen'

    person.objects.bulk_update(people, ['age_group'])

def reverse_age_group(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')
    people = person.objects.all()

    for p in people:
        p.age_group = person._meta.get_field('age group').default

    person.objects.bulk_update(people, ['age_group'])

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_course'),
    ]

    operations = [
        migrations.RunPython(change_age_group, reverse_age_group)
    ]
