# Generated by Django 5.0.4 on 2025-02-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_person'),
        ('main_app', '0008_auto_20250219_1653'),
    ]

    operations = [
    ]
