# Generated by Django 5.0.4 on 2025-02-19 19:17

from django.db import migrations


def change_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    items = item_model.objects.all()

    for i in items:
        if i.price <= 10:
            i.rarity = 'Rare'
        elif 11 <= i.price <= 20:
            i.rarity = 'Very Rare'
        elif 21 <= i.price <= 31:
            i.rarity = 'Extremely Rare'
        else:
            i.rarity = 'Mega Rare'

    item_model.objects.bulk_update(items, ['rarity'])

def make_rarity_default(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    items = item_model.objects.all()

    for i in items:
        i.rarity = item_model._meta.get_field('rarity').default

    item_model.objects.bulk_update(items, ['rarity'])

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_item'),
    ]

    operations = [
        migrations.RunPython(change_rarity, make_rarity_default)
    ]
