# Generated by Django 5.0.4 on 2025-02-19 19:49

from django.db import migrations


def new_price(apps, schema_editor):
    DEFAULT_MULTIPLIER = 120
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    for smp in smartphones:
        smp.price = len(smp.brand) * DEFAULT_MULTIPLIER

    smartphone_model.objects.bulk_update(smartphones, ['price'])


def new_value(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    for smp in smartphones:
        if smp.price >= 750:
            smp.category = 'Expensive'
        else:
            smp.category = 'Cheap'

    smartphone_model.objects.bulk_update(smartphones, ['category'])


def make_default_price_and_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    smartphones = smartphone_model.objects.all()

    for smp in smartphones:
        smp.category = smartphone_model._meta.get_field('category').default
        smp.price = 0

    smartphone_model.objects.bulk_update(smartphones, ['category'])
    smartphone_model.objects.bulk_update(smartphones, ['price'])


def call_price_and_category(apps, schema_editor):
    new_price(apps, schema_editor)
    new_value(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0012_smartphone'),
    ]

    operations = [
        migrations.RunPython(call_price_and_category, make_default_price_and_category),
    ]
