# Generated by Django 5.0.4 on 2025-02-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20250219_2149'),
        ('main_app', '0014_auto_20250219_2210'),
    ]

    operations = [
    ]
