# Generated by Django 5.0.4 on 2025-02-20 08:50
from datetime import timedelta

from django.db import migrations

from main_app.choices import Statuses


def changing_delivery_and_warranty(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')
    orders = order_model.objects.all()

    for order in orders:
        if order.status == Statuses.PENDING:
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status == Statuses.COMPLETED:
            order.warranty = '24 months'
            order.save()
        elif order.status == Statuses.CANCELLED:
            order.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_order'),
    ]

    operations = [
        migrations.RunPython(code=changing_delivery_and_warranty)
    ]
