# Generated by Django 5.0.4 on 2025-02-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20250220_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('COM', 'Completed'), ('CAN', 'Cancelled')], max_length=30),
        ),
    ]
