# Generated by Django 5.0.4 on 2025-03-07 08:13

import main_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', main_app.fields.MaskedEmployeeIDField(max_length=15)),
            ],
        ),
    ]
