# Generated by Django 5.0.4 on 2025-02-19 10:47
import random
from django.db import migrations


def make_changes(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    products = Product.objects.all()
    barcodes = random.sample(range(100000000, 1000000000), len(products))

    for i in range(len(products)):
        product =  products[i]
        product.barcode = barcodes[i]
        product.save()


def reverse_changes(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    products = Product.objects.all()

    for p in products:
        p.barcode = 0
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_product_barcode'),
    ]
    operations = [
        migrations.RunPython(make_changes, reverse_code=reverse_changes)
    ]
