# Generated by Django 5.0.4 on 2025-02-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_studentenrollment_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
