# Generated by Django 5.0.4 on 2025-02-28 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_studentenrollment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
